"""Change inbox model

Revision ID: 2035053107c7
Revises: ea3d36d045c2
Create Date: 2021-05-07 22:21:02.808289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2035053107c7'
down_revision = 'ea3d36d045c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('inbox', sa.Column('title', sa.Text(), nullable=True))
    op.drop_column('inbox', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('inbox', 'title')
    op.drop_column('inbox', 'message')
    # ### end Alembic commands ###
