"""Inbox model alter

Revision ID: 840d4495c99d
Revises: 2035053107c7
Create Date: 2021-05-15 22:04:30.505975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840d4495c99d'
down_revision = '2035053107c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('parent_message', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inbox', 'inbox', ['parent_message'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox', type_='foreignkey')
    op.drop_column('inbox', 'parent_message')
    # ### end Alembic commands ###
