"""fix

Revision ID: d2db90b0e065
Revises: fed063ba4707
Create Date: 2021-05-18 21:04:46.010054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2db90b0e065'
down_revision = 'fed063ba4707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('user_dis_follow_id', sa.Integer(), nullable=True))
    op.add_column('discussion', sa.Column('user_dis_start_id', sa.Integer(), nullable=True))
    op.drop_constraint('discussion_user_dis_follow_fkey', 'discussion', type_='foreignkey')
    op.drop_constraint('discussion_user_dis_start_fkey', 'discussion', type_='foreignkey')
    op.create_foreign_key(None, 'discussion', 'users', ['user_dis_start_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'discussion', 'users', ['user_dis_follow_id'], ['id'], ondelete='cascade')
    op.drop_column('discussion', 'user_dis_start')
    op.drop_column('discussion', 'user_dis_follow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('user_dis_follow', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('discussion', sa.Column('user_dis_start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'discussion', type_='foreignkey')
    op.drop_constraint(None, 'discussion', type_='foreignkey')
    op.create_foreign_key('discussion_user_dis_start_fkey', 'discussion', 'users', ['user_dis_start'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('discussion_user_dis_follow_fkey', 'discussion', 'users', ['user_dis_follow'], ['id'], ondelete='CASCADE')
    op.drop_column('discussion', 'user_dis_start_id')
    op.drop_column('discussion', 'user_dis_follow_id')
    # ### end Alembic commands ###
