"""discussion model with many to many

Revision ID: fed063ba4707
Revises: 840d4495c99d
Create Date: 2021-05-17 20:34:19.644648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed063ba4707'
down_revision = '840d4495c99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_dis_start', sa.Integer(), nullable=True),
    sa.Column('user_dis_follow', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_dis_follow'], ['users.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_dis_start'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox_discussion_rel',
    sa.Column('discussion_id', sa.Integer(), nullable=True),
    sa.Column('inbox_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], ),
    sa.ForeignKeyConstraint(['inbox_id'], ['inbox.id'], )
    )
    op.drop_constraint('inbox_parent_message_fkey', 'inbox', type_='foreignkey')
    op.drop_column('inbox', 'parent_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('parent_message', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('inbox_parent_message_fkey', 'inbox', 'inbox', ['parent_message'], ['id'], ondelete='CASCADE')
    op.drop_table('inbox_discussion_rel')
    op.drop_table('discussion')
    # ### end Alembic commands ###
